"""Generate report-ready PNG figures from the same model outputs used by the app.

The script deliberately avoids hand-entered chart values. Every figure reads from
`outputs/tables/*.csv` generated by `scripts/generate_outputs.py`, except the
Q-learning reward trace which is regenerated with the same default seed used by
the app and output script.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
TABLE_DIR = ROOT / "outputs" / "tables"
FIGURE_DIR = ROOT / "outputs" / "figures"

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from aideom_vn.config import ensure_output_dirs
from aideom_vn.exercise11_qlearning import train_q_learning


COLORS = {
    "blue": "#2563eb",
    "sky": "#38bdf8",
    "teal": "#0f766e",
    "green": "#16a34a",
    "amber": "#d97706",
    "red": "#dc2626",
    "slate": "#334155",
    "gray": "#94a3b8",
}


FIGURES: list[dict[str, str]] = []


def read_table(name: str) -> pd.DataFrame:
    path = TABLE_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run `python scripts/generate_outputs.py` first."
        )
    return pd.read_csv(path)


def setup_style() -> None:
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 220,
            "font.family": "DejaVu Sans",
            "axes.titlesize": 15,
            "axes.titleweight": "bold",
            "axes.labelsize": 11,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "axes.grid": True,
            "grid.alpha": 0.22,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
        }
    )


def save_current(filename: str, title: str, source: str, model: str, note: str) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    path = FIGURE_DIR / filename
    plt.tight_layout()
    plt.savefig(path, bbox_inches="tight")
    plt.close()
    FIGURES.append(
        {
            "file": filename,
            "title": title,
            "source": source,
            "model": model,
            "note": note,
        }
    )
    print(path)


def horizontal_bar(
    df: pd.DataFrame,
    x: str,
    y: str,
    title: str,
    xlabel: str,
    filename: str,
    source: str,
    model: str,
    note: str,
    color: str = COLORS["blue"],
) -> None:
    plot_df = df.copy()
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    ax.barh(plot_df[y], plot_df[x], color=color)
    ax.invert_yaxis()
    ax.set_title(title, loc="left")
    ax.set_xlabel(xlabel)
    ax.set_ylabel("")
    for i, value in enumerate(plot_df[x]):
        ax.text(value, i, f" {value:,.2f}", va="center", fontsize=8)
    save_current(filename, title, source, model, note)


def figure_01() -> None:
    df = read_table("bai01_cobb_douglas.csv")
    contrib = read_table("bai01_growth_accounting.csv")

    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    ax.plot(df["year"], df["TFP_A_t"], marker="o", linewidth=2.5, color=COLORS["teal"])
    ax.set_title("Bài 1 - Xu hướng TFP A_t giai đoạn 2020-2025", loc="left")
    ax.set_xlabel("Năm")
    ax.set_ylabel("TFP A_t")
    save_current(
        "bai01_tfp_trend.png",
        "Bài 1 - Xu hướng TFP A_t",
        "bai01_cobb_douglas.csv",
        "run_cobb_douglas()",
        "TFP tính ngược từ hàm Cobb-Douglas mở rộng.",
    )

    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    ax.plot(df["year"], df["Y"], marker="o", linewidth=2.5, label="GDP thực tế", color=COLORS["blue"])
    ax.plot(df["year"], df["Y_hat"], marker="s", linewidth=2.5, label="GDP dự báo", color=COLORS["amber"])
    ax.set_title("Bài 1 - GDP thực tế và GDP dự báo", loc="left")
    ax.set_xlabel("Năm")
    ax.set_ylabel("Nghìn tỷ VND")
    ax.legend(frameon=False)
    save_current(
        "bai01_actual_vs_predicted_gdp.png",
        "Bài 1 - GDP thực tế và dự báo",
        "bai01_cobb_douglas.csv",
        "run_cobb_douglas()",
        "So sánh GDP thực tế với GDP dự báo bằng TFP trung bình.",
    )

    horizontal_bar(
        contrib.sort_values("share_of_growth_pct", ascending=True),
        "share_of_growth_pct",
        "factor",
        "Bài 1 - Tỷ trọng đóng góp tăng trưởng",
        "Tỷ trọng đóng góp (%)",
        "bai01_growth_contribution.png",
        "bai01_growth_accounting.csv",
        "growth_contribution()",
        "Phân rã tăng trưởng theo TFP, K, L, D, AI và H.",
        COLORS["teal"],
    )


def figure_02() -> None:
    alloc = read_table("bai02_allocation.csv")
    sens = read_table("bai02_sensitivity.csv")

    fig, ax = plt.subplots(figsize=(8.5, 5.2))
    bars = ax.bar(alloc["item"], alloc["allocation"], color=[COLORS["blue"], COLORS["sky"], COLORS["green"], COLORS["amber"]])
    ax.set_title("Bài 2 - Phân bổ ngân sách tối ưu", loc="left")
    ax.set_ylabel("Nghìn tỷ VND")
    ax.set_xlabel("Hạng mục")
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{bar.get_height():.1f}", ha="center", va="bottom")
    save_current(
        "bai02_budget_allocation.png",
        "Bài 2 - Phân bổ ngân sách tối ưu",
        "bai02_allocation.csv",
        "solve_simple_budget_lp()",
        "Nghiệm LP cho bốn hạng mục đầu tư số.",
    )

    fig, ax = plt.subplots(figsize=(8.5, 5.2))
    ax.plot(sens["budget"], sens["objective"], marker="o", linewidth=2.5, color=COLORS["teal"])
    ax.set_title("Bài 2 - Đường cong độ nhạy Z*(B)", loc="left")
    ax.set_xlabel("Ngân sách B (nghìn tỷ VND)")
    ax.set_ylabel("GDP gain tối ưu")
    save_current(
        "bai02_sensitivity_curve.png",
        "Bài 2 - Độ nhạy ngân sách",
        "bai02_sensitivity.csv",
        "sensitivity_by_budget()",
        "Giá trị mục tiêu tối ưu khi tăng ngân sách tổng.",
    )


def figure_03() -> None:
    ranked = read_table("bai03_priority.csv").sort_values("priority_score", ascending=True)
    horizontal_bar(
        ranked,
        "priority_score",
        "sector_name_vi",
        "Bài 3 - Xếp hạng ưu tiên 10 ngành",
        "Điểm ưu tiên",
        "bai03_priority_ranking.png",
        "bai03_priority.csv",
        "run_priority_model()",
        "Chỉ số ưu tiên sau chuẩn hóa min-max và trọng số chính sách.",
        COLORS["blue"],
    )


def figure_04() -> None:
    region = read_table("bai04_region_summary.csv").sort_values("allocation", ascending=True)
    item = read_table("bai04_item_summary.csv").sort_values("allocation", ascending=False)
    horizontal_bar(
        region,
        "allocation",
        "region_name_vi",
        "Bài 4 - Phân bổ ngân sách theo vùng",
        "Tỷ VND",
        "bai04_region_allocation.png",
        "bai04_region_summary.csv",
        "solve_region_sector_lp()",
        "Tổng phân bổ sau ràng buộc công bằng vùng miền.",
        COLORS["teal"],
    )

    fig, ax = plt.subplots(figsize=(8.5, 5.2))
    ax.pie(item["allocation"], labels=item["item_name"], autopct="%1.1f%%", startangle=90)
    ax.set_title("Bài 4 - Cơ cấu phân bổ theo hạng mục", loc="left")
    save_current(
        "bai04_item_mix.png",
        "Bài 4 - Cơ cấu hạng mục",
        "bai04_item_summary.csv",
        "solve_region_sector_lp()",
        "Tỷ trọng ngân sách theo I, D, AI và H.",
    )


def figure_05() -> None:
    selected = read_table("bai05_selected_projects.csv").sort_values("benefit", ascending=True)
    horizontal_bar(
        selected,
        "benefit",
        "project_name",
        "Bài 5 - Lợi ích các dự án được chọn",
        "Lợi ích NPV kỳ vọng",
        "bai05_selected_projects.png",
        "bai05_selected_projects.csv",
        "solve_project_mip() / PuLP_CBC",
        "Danh mục dự án tối ưu dưới ngân sách, rủi ro và ràng buộc logic.",
        COLORS["green"],
    )


def figure_06() -> None:
    ranking = read_table("bai06_topsis.csv").sort_values("TOPSIS_score", ascending=True)
    horizontal_bar(
        ranking,
        "TOPSIS_score",
        "region_name_vi",
        "Bài 6 - TOPSIS xếp hạng ưu tiên vùng AI",
        "TOPSIS score",
        "bai06_topsis_ranking.png",
        "bai06_topsis.csv",
        "run_topsis()",
        "Điểm gần phương án lý tưởng tốt theo TOPSIS.",
        COLORS["blue"],
    )


def figure_07() -> None:
    pareto = read_table("bai07_pareto.csv")
    sample = pareto.sample(min(len(pareto), 3500), random_state=42)
    fig, ax = plt.subplots(figsize=(9.5, 5.6))
    scatter = ax.scatter(
        sample["gdp_gain"],
        sample["inclusion"],
        c=sample["risk_index"],
        s=18,
        cmap="viridis",
        alpha=0.75,
    )
    ax.set_title("Bài 7 - Pareto frontier giữa GDP gain và bao trùm", loc="left")
    ax.set_xlabel("GDP gain")
    ax.set_ylabel("Inclusion score")
    fig.colorbar(scatter, ax=ax, label="Risk index")
    save_current(
        "bai07_pareto_frontier.png",
        "Bài 7 - Pareto frontier",
        "bai07_pareto.csv",
        "run_pareto_search() / pymoo.NSGA2",
        "Mẫu cố định từ tập nghiệm Pareto để báo cáo dễ đọc.",
    )


def figure_08() -> None:
    trajectory = read_table("bai08_dynamic_trajectory.csv")
    baseline = read_table("bai08_baseline_trajectory.csv")
    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    ax.plot(trajectory["year"], trajectory["GDP"], marker="o", linewidth=2.5, color=COLORS["teal"], label="Toi uu")
    ax.plot(baseline["year"], baseline["GDP"], marker="s", linewidth=2.1, color=COLORS["blue"], label="Can bang co dinh")
    ax.set_title("Bài 8 - Quỹ đạo GDP tối ưu 2026-2035", loc="left")
    ax.set_xlabel("Năm")
    ax.set_ylabel("GDP mô phỏng")
    ax.legend(frameon=False)
    save_current(
        "bai08_gdp_path_2026_2035.png",
        "Bài 8 - Quỹ đạo GDP 2026-2035",
        "bai08_dynamic_trajectory.csv + bai08_baseline_trajectory.csv",
        "optimize_dynamic_policy() / CVXPY-or-SLSQP",
        "Đường GDP dưới mô hình tối ưu liên thời gian formal.",
    )


def figure_09() -> None:
    labor = read_table("bai09_labor_impact.csv").sort_values("net_job_million", ascending=True)
    colors = [COLORS["red"] if value < 0 else COLORS["green"] for value in labor["net_job_million"]]
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    ax.barh(labor["sector_name_vi"], labor["net_job_million"], color=colors)
    ax.axvline(0, color=COLORS["slate"], linewidth=1.2)
    ax.set_title("Bài 9 - NetJob theo ngành dưới tác động AI", loc="left")
    ax.set_xlabel("Triệu việc làm")
    ax.set_ylabel("")
    save_current(
        "bai09_netjob_by_sector.png",
        "Bài 9 - NetJob theo ngành",
        "bai09_labor_impact.csv",
        "simulate_labor_impact()",
        "NetJob = việc làm mới + việc làm giữ lại - việc làm mất đi.",
    )


def figure_10() -> None:
    scenarios = read_table("bai10_scenario_values.csv")
    fig, ax = plt.subplots(figsize=(8.5, 5.2))
    bars = ax.bar(scenarios["scenario"], scenarios["value"], color=[COLORS["green"], COLORS["blue"], COLORS["amber"]])
    ax.set_title("Bài 10 - Giá trị chính sách theo kịch bản", loc="left")
    ax.set_xlabel("Kịch bản")
    ax.set_ylabel("Giá trị")
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{bar.get_height():,.0f}", ha="center", va="bottom", fontsize=8)
    save_current(
        "bai10_scenario_values.png",
        "Bài 10 - Giá trị theo kịch bản",
        "bai10_scenario_values.csv",
        "solve_stochastic_policy() / Pyomo appsi_highs",
        "Giá trị quyết định stochastic trong ba trạng thái bất định.",
    )


def figure_11() -> None:
    q = read_table("bai11_q_table.csv").set_index("state")
    fig, ax = plt.subplots(figsize=(9.5, 4.8))
    im = ax.imshow(q.to_numpy(), cmap="Blues")
    ax.set_xticks(np.arange(len(q.columns)), q.columns, rotation=25, ha="right")
    ax.set_yticks(np.arange(len(q.index)), q.index)
    ax.set_title("Bài 11 - Q-table sau huấn luyện", loc="left")
    for i in range(q.shape[0]):
        for j in range(q.shape[1]):
            ax.text(j, i, f"{q.iloc[i, j]:.0f}", ha="center", va="center", fontsize=8)
    fig.colorbar(im, ax=ax, label="Q value")
    save_current(
        "bai11_q_table_heatmap.png",
        "Bài 11 - Q-table heatmap",
        "bai11_q_table.csv",
        "train_q_learning()",
        "Giá trị Q theo trạng thái và hành động.",
    )

    reward = train_q_learning()["reward_trace"]
    reward["rolling_reward"] = reward["reward"].rolling(30, min_periods=1).mean()
    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    ax.plot(reward["episode"], reward["reward"], color=COLORS["gray"], alpha=0.35, label="Reward")
    ax.plot(reward["episode"], reward["rolling_reward"], color=COLORS["teal"], linewidth=2.5, label="Rolling mean")
    ax.set_title("Bài 11 - Reward trace Q-learning", loc="left")
    ax.set_xlabel("Episode")
    ax.set_ylabel("Reward")
    ax.legend(frameon=False)
    save_current(
        "bai11_reward_trace.png",
        "Bài 11 - Reward trace",
        "train_q_learning() regenerated with default seed",
        "train_q_learning()",
        "Reward được tái tạo bằng cùng seed mặc định để phục vụ báo cáo.",
    )


def figure_12() -> None:
    scenarios = read_table("bai12_scenarios.csv")
    fig, (ax, ax2) = plt.subplots(2, 1, figsize=(10.5, 8.2), gridspec_kw={"height_ratios": [2.0, 1.15]})
    x = np.arange(len(scenarios))
    width = 0.35
    ax.bar(x - width / 2, scenarios["GDP_gain"], width, label="GDP gain", color=COLORS["blue"])
    ax.bar(x + width / 2, scenarios["inclusion"], width, label="Bao trùm", color=COLORS["sky"])
    ax.set_title("Bài 12 - So sánh 6 kịch bản chính sách", loc="left")
    ax.set_xticks(x, [])
    ax.set_ylabel("Giá trị KPI")
    ax.legend(frameon=False)
    net_colors = [COLORS["green"] if value >= 0 else COLORS["red"] for value in scenarios["net_job_million"]]
    ax2.bar(x, scenarios["net_job_million"], color=net_colors)
    ax2.axhline(0, color=COLORS["slate"], linewidth=1.2)
    ax2.set_xticks(x, scenarios["scenario"], rotation=18, ha="right")
    ax2.set_ylabel("NetJob (trieu)")
    save_current(
        "bai12_scenario_comparison.png",
        "Bài 12 - So sánh kịch bản",
        "bai12_scenarios.csv",
        "evaluate_scenarios()",
        "So sánh GDP gain, KPI bao trùm và NetJob của 6 kịch bản.",
    )


def write_index() -> None:
    lines = [
        "# Figure Index",
        "",
        "Các hình trong thư mục này được sinh tự động bằng `scripts/generate_figures.py`.",
        "Nguồn số liệu là các CSV trong `outputs/tables/` được sinh bởi `scripts/generate_outputs.py`.",
        "",
        "| File | Tiêu đề | Nguồn | Model | Ghi chú |",
        "|---|---|---|---|---|",
    ]
    for fig in FIGURES:
        lines.append(
            f"| `{fig['file']}` | {fig['title']} | `{fig['source']}` | `{fig['model']}` | {fig['note']} |"
        )
    (FIGURE_DIR / "FIGURE_INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(FIGURE_DIR / "FIGURE_INDEX.md")


def main() -> None:
    ensure_output_dirs()
    setup_style()
    figure_01()
    figure_02()
    figure_03()
    figure_04()
    figure_05()
    figure_06()
    figure_07()
    figure_08()
    figure_09()
    figure_10()
    figure_11()
    figure_12()
    write_index()


if __name__ == "__main__":
    main()
